experiment_id: toy_noise_identifiability
backend: toy
task: classification

training:
  n_samples: 200
  n_features: 2
  n_epochs: 150
  learning_rate: 0.1
  train_frac: 0.8

verification:
  accuracy_threshold: 0.7
  ident_threshold: 0.1

noise:
  amplitude_gamma: 0.01

sweep:
  depolarizing_p: [0.0, 0.05, 0.1, 0.15, 0.2]
  measurement_bitflip_p: [0.0, 0.05, 0.1, 0.15, 0.2]
